{"uuid": "c4847602-498a-433e-a688-eb04f5172032", "children": ["e108820c-560a-480f-839c-fc8c813ea4a1"], "befores": [{"name": "_xunit_setup_function_fixture_script", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x5f6dff82eb9a <unknown>\n#1 0x5f6dff514670 <unknown>\n#2 0x5f6dff54c971 <unknown>\n#3 0x5f6dff548315 <unknown>\n#4 0x5f6dff594e66 <unknown>\n#5 0x5f6dff5944b6 <unknown>\n#6 0x5f6dff588923 <unknown>\n#7 0x5f6dff5566e7 <unknown>\n#8 0x5f6dff5576de <unknown>\n#9 0x5f6dff7f866b <unknown>\n#10 0x5f6dff7fc611 <unknown>\n#11 0x5f6dff7e44e5 <unknown>\n#12 0x5f6dff7fd192 <unknown>\n#13 0x5f6dff7c96ef <unknown>\n#14 0x5f6dff81d9d8 <unknown>\n#15 0x5f6dff81dba7 <unknown>\n#16 0x5f6dff82d9ec <unknown>\n#17 0x7d4200094ac3 <unknown>\n\n", "trace": "  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/_pytest/python.py\", line 610, in xunit_setup_function_fixture\n    _call_with_optional_argument(setup_function, function)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/_pytest/python.py\", line 717, in _call_with_optional_argument\n    func()\n  File \"/home/saim/al-nafi-diploma-devops/Python_selenium/pytest-with-jenkins/script.py\", line 26, in setup_function\n    driver=webdriver.Chrome(service=service)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py\", line 45, in __init__\n    super().__init__(\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py\", line 66, in __init__\n    super().__init__(command_executor=executor, options=options)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 212, in __init__\n    self.start_session(capabilities)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 299, in start_session\n    response = self.execute(Command.NEW_SESSION, caps)[\"value\"]\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"/var/lib/jenkins/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1730621910245, "stop": 1730621912627}], "start": 1730621910244, "stop": 1730621912788}